#!/usr/bin/env ruby
require 'd_script'
require 'slop'

opts = Slop.parse do
  on :n, :name=, 'batch name'
  on :N, :num_runners=, 'batch name'
  on :e, :env=, 'environment'
  on :r, :redis=, 'redis url'
end.to_hash

script = ARGV[0]
name = opts[:name]
num_runners = opts[:num_runners] || 1000
env = opts[:env] || 'development'
redis_settings = { url: opts[:redis] || "redis://localhost:6379" }

puts "d_script:slave started with name=#{name} env=#{env}"

slave = DScript::Slave.new(name, redis_settings)
slave.run(num_runners, env)

puts "done"
